services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: impact_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    image: eclipse-temurin:21-jdk
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run
    depends_on:
      - db
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/impact_db
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: userpassword
volumes:
  db_data: