services:
  dbservice:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: impact_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    image: eclipse-temurin:21-jdk
    working_dir: /app
    volumes:
      - .:/app
      - .mavencache:/root/.m2
    ports:
      - "8080:8080"
    command: ./launcher.sh
    env_file:
      - .env
    depends_on:
      - dbservice
    environment:
        DATASOURCE_URL: jdbc:postgresql://dbservice:5432/impact_db
        DATASOURCE_USERNAME: user
        DATASOURCE_PASSWORD: userpassword
volumes:
  db_data:
