services:
  dbservice:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    image: eclipse-temurin:21-jdk
    working_dir: /app
    volumes:
      - .:/app
      - .mavencache:/root/.m2
    ports:
      - "8080:8080"
      - "5005:5005"
    command: ./launcher.sh
    env_file:
      - .env
    depends_on:
      - dbservice
volumes:
  db_data:
